import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {randomUUID} from "node:crypto";
import {beforeEach,afterEach,it,expect,vi} from "vitest";
const mocks=vi.hoisted(()=>({prepare:vi.fn(),execute:vi.fn()}));
vi.mock("../lib/trading/prepare",()=>({preparePurchase:mocks.prepare}));
vi.mock("../lib/trading/agent-execute",()=>({executeAgentPurchase:mocks.execute}));
import {runAccount} from "../lib/dca/runtime/engine";
import {writeStrategy,readStrategy,requestPause} from "../lib/dca/runtime/store";
import {persistResult,readQuote} from "../lib/trading/journal";
import {runtimeInput,type RuntimeStrategy} from "../lib/dca/runtime/types";
const account=`0x${"1".repeat(40)}`;const now=Date.parse("2027-01-01T12:00:00Z");let dir:string;
const state=():RuntimeStrategy=>({id:randomUUID(),plan:{version:1,account,market:"spot",amount:50,budget:100,btcPercent:100,frequency:"daily",startAt:new Date(now).toISOString(),status:"draft"},slippageBps:50,status:"running",nextIndex:0,reservedUSDC:0,createdAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString(),runs:[]});
beforeEach(()=>{dir=mkdtempSync(join(tmpdir(),"dca-worker-"));vi.stubEnv("AGENT_DATA_DIR",dir);mocks.prepare.mockReset();mocks.execute.mockReset();mocks.prepare.mockImplementation(async()=>({id:randomUUID(),account,amount:50,btcPercent:100,slippageBps:50,expiresAt:Date.now()+60000,availableUSDC:"100",maxDebit:"50",blockers:[],legs:[{symbol:"UBTC",asset:10142,coin:"@142",price:"100000",size:"0.0004",notional:"40",referenceAsk:"99999",cloid:`0x${"a".repeat(32)}`}]}));mocks.execute.mockImplementation(async(_a:string,id:string)=>({quote:readQuote(id),state:"result",updatedAt:new Date().toISOString(),response:{status:"ok",response:{data:{statuses:[{filled:{totalSz:"0.0004"}}]}}}}));});
afterEach(()=>{rmSync(dir,{recursive:true,force:true});vi.unstubAllEnvs();});
it("runs once per slot and stops at the authorized budget",async()=>{writeStrategy(state());await runAccount(account,now);await runAccount(account,now);expect(mocks.execute).toHaveBeenCalledTimes(1);await runAccount(account,now+86400000);await runAccount(account,now+2*86400000);expect(mocks.execute).toHaveBeenCalledTimes(2);expect(readStrategy(account)).toMatchObject({status:"completed",reservedUSDC:100,nextIndex:2});});
it("does not execute before the first slot",async()=>{writeStrategy(state());await runAccount(account,now-1);expect(mocks.execute).not.toHaveBeenCalled();});
it("skips missed slots without catch-up bursts",async()=>{writeStrategy(state());await runAccount(account,now+86400000);expect(mocks.execute).toHaveBeenCalledTimes(1);expect(readStrategy(account)?.runs[0].state).toBe("skipped");expect(readStrategy(account)?.reservedUSDC).toBe(50);});
it("honors pause before preparation",async()=>{writeStrategy(state());requestPause(account);await runAccount(account,now);expect(mocks.prepare).not.toHaveBeenCalled();expect(readStrategy(account)?.status).toBe("paused");});
it("honors pause while preparing",async()=>{const original=mocks.prepare.getMockImplementation()!;mocks.prepare.mockImplementation(async()=>{requestPause(account);return original();});writeStrategy(state());await runAccount(account,now);expect(mocks.execute).not.toHaveBeenCalled();expect(readStrategy(account)?.status).toBe("paused");});
it("reserves budget before any execution request",async()=>{writeStrategy(state());mocks.execute.mockImplementation(async()=>{expect(readStrategy(account)?.reservedUSDC).toBe(50);throw new Error("interrupted");});await runAccount(account,now);expect(readStrategy(account)?.status).toBe("blocked");});
it("blocks on uncertain results and never retries that slot",async()=>{mocks.execute.mockImplementation(async(_a:string,id:string)=>({quote:readQuote(id),state:"unknown",updatedAt:new Date().toISOString()}));writeStrategy(state());await runAccount(account,now);await runAccount(account,now+86400000);expect(mocks.execute).toHaveBeenCalledTimes(1);expect(readStrategy(account)?.status).toBe("blocked");});
it("blocks partial fills for review",async()=>{mocks.execute.mockImplementation(async(_a:string,id:string)=>({quote:readQuote(id),state:"result",updatedAt:new Date().toISOString(),response:{status:"ok",response:{data:{statuses:[{filled:{totalSz:"0.0001"}}]}}}}));writeStrategy(state());await runAccount(account,now);expect(readStrategy(account)?.status).toBe("blocked");});
it("serializes concurrent worker ticks",async()=>{writeStrategy(state());await Promise.all([runAccount(account,now),runAccount(account,now)]);expect(mocks.execute).toHaveBeenCalledTimes(1);});
it("recovers a completed journal result without re-executing",async()=>{const s=state();const q=await mocks.prepare();s.nextIndex=1;s.reservedUSDC=50;s.runs=[{index:0,dueAt:s.plan.startAt,state:"pending",quoteId:q.id}];writeStrategy(s);persistResult({quote:q,state:"result",updatedAt:new Date().toISOString(),response:{status:"ok",response:{data:{statuses:[{filled:{totalSz:"0.0004"}}]}}}});await runAccount(account,now);expect(mocks.execute).not.toHaveBeenCalled();expect(readStrategy(account)?.runs[0].state).toBe("result");});
it("rejects sub-cent budget and excessive slippage",()=>{expect(()=>runtimeInput.parse({plan:{...state().plan,amount:10.001},slippageBps:50})).toThrow();expect(()=>runtimeInput.parse({plan:state().plan,slippageBps:200})).toThrow();});
